Fix type errors
Traceback (most recent call last):
  File "/home/gal/bin/msmtpq_notify.py", line 85, in <module>
    NR_OF_ENTRIES_BEFORE = get_nr_of_entries_in_queue()
  File "/home/gal/bin/msmtpq_notify.py", line 46, in get_nr_of_entries_in_queue
    if line.find("  mail id = [ ") == 0:
TypeError: a bytes-like object is required, not 'str

Traceback (most recent call last):
  File "/home/gal/bin/msmtpq_notify.py", line 90, in <module>
    RETURN_CODE = call_msmtpq()
  File "/home/gal/bin/msmtpq_notify.py", line 75, in call_msmtpq
    proc.stdin.write(line)
TypeError: a bytes-like object is required, not 'str'